### ISSUE TITLE
Discord link broken

### ISSUE THREAD

**Issue by zaspy** [victti/BSGO-Private-Server#5]
would like to join the discord but link doesnt work. can a new one be posted? also, where can you get a client?

**Comment by oshtolz** [comment]
> would like to join the discord but link doesnt work. can a new one be posted? also, where can you get a client?

https://discord.gg/52eJ3s

**Comment by victti** [comment]
Project is no longer maintained and it shutdown months ago.

**Comment by HRoberto195** [comment]
Dear Victti . Pls sahe the working server .. Many thanks  BSGO  FANS

**Comment by DiabolSVK** [comment]
Hello, I'm a big BSGO fan.

But I don't know English and google translator confuses words

**Comment by HRoberto195** [comment]
No Problem DiabolosSVK .   I loocking for the server file .   Okay hire is one  but this is no working from online + weapon system .
